name: Run BGMI Workflow (Long Running)

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  run-workflow:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # 6 hours max run time
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install packages
        run: |
          pip install telebot flask aiogram pyTelegramBotAPI python-telegram-bot pytest
      
      - name: Set permissions
        run: chmod +x *
      
      - name: Run Python script
        run: python3 m.py
      
      - name: Keep running
        run: |
          while true; do
            echo "Workflow is running - $(date)"
            sleep 60
          done
